version: '3.9'

services:
  whoami:
    image: traefik/whoami
    command:
      - --port=8000
      - -verbose
    ports:
      - 8000:8000
  proxy:
    image: traefik:v2.9.5
    command:
      - "--providers.file.directory=/config"
      - "--experimental.localPlugins.cookiesmanager.moduleName=github.com/theoguidoux/cookiesmanager"
      - "--entrypoints.web=true"
      - "--entryPoints.web.address=:8001"
      - "--log=true"
      - "--log.level=DEBUG"
    volumes:
      - ./test-traefik-config.yaml:/config/config.yaml:ro
      - ../:/plugins-local/src/github.com/theoguidoux/cookiesmanager:ro
    ports:
      - 8001:8001
